name: Deploy to ECR (INT/PROD)

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Choose the version to deploy (patch, minor, major)'
        required: true
        default: 'patch'  # You can have options: patch, minor, major
      environment:
        description: 'Select the environment to deploy (INT or PROD)'
        required: true
        default: 'INT'  # Default can be INT, but user can change it
        type: choice
        options:
          - INT
          - PROD

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: github-sample

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get the current version tag from the latest Git tag
      id: get_git_tag
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "Current tag: $TAG"
        TAG=$(git describe --tags --abbrev=0 || echo "v1.0.0")
        echo "Current tag: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Update version based on user input
      id: update_version
      run: |
        version_parts=(${TAG//./ })
        if [ "${{ github.event.inputs.version }}" == "patch" ]; then
          version_parts[2]=$((version_parts[2]+1))  # Increment patch version
        elif [ "${{ github.event.inputs.version }}" == "minor" ]; then
          version_parts[1]=$((version_parts[1]+1))  # Increment minor version
          version_parts[2]=0  # Reset patch version
        else
          version_parts[0]=$((version_parts[0]+1))  # Increment major version
          version_parts[1]=0  # Reset minor version
          version_parts[2]=0  # Reset patch version
        fi
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"
        echo "TAG=$new_version" >> $GITHUB_ENV
        echo $TAG

    - name: Set Git user identity (local)
      run: |
        git config user.name "Prashu106"
        git config user.email "prashusaxena23@gmail.com"

    - name: Set up GitHub authentication
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/Prashu106/sample-github-actions.git


    - name: Tag the Git repository with the new version
      run: |
        git tag -a ${{ env.TAG }} -m "Deploying version ${{ env.TAG }}"
        git push origin ${{ env.TAG }}

    - name: Tag and Build Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        if [ "${{ github.event.inputs.environment }}" == "INT" ]; then
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
        elif [ "${{ github.event.inputs.environment }}" == "PROD" ]; then
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG .
        fi

    - name: Push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        if [ "${{ github.event.inputs.environment }}" == "INT" ]; then
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        elif [ "${{ github.event.inputs.environment }}" == "PROD" ]; then
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
        fi
