name: Manual Build and Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (INT or PROD)'
        required: true
        type: choice
        options:
          - INT
          - PROD

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      ECR_REPOSITORY: github-sample

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 3: Checkout the specific tag that the user selected
    - name: retrieve the tag
      run: |
        # Use cut to remove the refs/tags/ prefix
        TAG_NAME=$(echo $GITHUB_REF | sed 's/^refs\/tags\///')
        echo "The tag that triggered the workflow is: $GITHUB_REF"
        echo "Extracted tag name: $TAG_NAME"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Step 2: Set environment-specific values and AWS credentials
    - name: Set environment-specific values and AWS credentials
      run: |
        ENVIRONMENT=${{ github.event.inputs.environment }}
        echo "Selected environment: $ENVIRONMENT"
        
        if [ "$ENVIRONMENT" == "INT" ]; then
          echo "Setting environment to INT"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        elif [ "$ENVIRONMENT" == "PROD" ]; then
          echo "Setting environment to PROD"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID_PROD }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}"
        else
          echo "Setting environment to DEV"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        
        fi

        # Export variables to make them accessible to subsequent steps
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    # Step 7: Build the Docker image with the selected tag
    - name: Build Docker image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG_NAME .

    # Step 9: Push Docker image to AWS ECR
    - name: Push Docker image to AWS ECR
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$TAG_NAME
