# This is a basic workflow that is manually triggered

name: Manual workflow
run-name: Deploy triggered by ${{ github.actor }}

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      forceBuild_OTMM:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Force OTMM build.'
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean
      forceBuild_OTDS:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Force OTDS build.'
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean
      forceBuild_RMA:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Force RMA build.'
        # Default value if no value is explicitly provided
        default: false
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: boolean


env:
  FORCE_BUILD_OTMM: ${{ inputs.forceBuild_OTMM }}
  FORCE_BUILD_OTDS: ${{ inputs.forceBuild_OTDS }}
  RMA_WORKING_DIRECTORY: rma-directory 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      changed_otmm: ${{ steps.otmm.outputs.changed }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      id: send_greeting
      run: echo "Hello ${{ inputs.forceBuild_OTMM }}"

    - name: otmm step
      id: otmm
      run: echo "otmm ${{env.FORCE_BUILD_OTMM}}"

    - name: otds step
      id: otds
      run: echo "otds ${{env.FORCE_BUILD_OTDS}}"

  rma-build: 

    if:  ${{ inputs.forceBuild_RMA }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.RMA_WORKING_DIRECTORY }}
    
    needs: setup
    steps: 
     - name: Check out code
       uses: actions/checkout@v2

     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

     - name: Build with Maven
       run: |
         mvn clean package -DskipTests
    
     - name: Upload JAR as artifact
       uses: actions/upload-artifact@v4
       with:
         name: app-jar
         path: ${{ github.workspace }}/${{ env.RMA_WORKING_DIRECTORY }}/target/  # adjust if your JAR is named differently



  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.RMA_WORKING_DIRECTORY }}
    name: Download JAR and Build Docker Image
    needs: rma-build  # Wait for previous job to finish
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download JAR from previous job
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ${{ github.workspace }}/${{ env.RMA_WORKING_DIRECTORY }}/target  # put it in same directory expected by Dockerfile

      - name: copy jar to lib directory
        run: |
          cp ${{ github.workspace }}/${{ env.RMA_WORKING_DIRECTORY }}/target/*.jar ./lib/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t my-app:latest .
      
      - name: Save Docker image to tar file
        run: docker save my-app:latest -o my-app.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ github.workspace }}/${{ env.RMA_WORKING_DIRECTORY }}/my-app.tar
      
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ${{ github.workspace }}/${{ env.RMA_WORKING_DIRECTORY }}