on:
  push:
    branches:
      - dev  # Automatically trigger on push to dev branch (after PR merge)
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment (INT or PROD)'
        required: true
        type: choice
        options:
          - INT
          - PROD
      version_type:
        description: 'Choose version type (major, minor, patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

     # Step to automatically push the image when PR is merged to DEV branch
    - name: Push image for DEV environment (latest tag)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: github-sample
      if: github.ref == 'refs/heads/dev'  # This runs only on push to DEV branch
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Docker image pushed to ECR with 'latest' tag."

    # Step to handle versioning and push to INT or PROD when workflow is manually triggered
    - name: Get latest tag and increment version
      if: github.event_name == 'workflow_dispatch'  # This runs only when the workflow is manually triggered
      run: |
        # Get the latest tag from git or fallback to 1.0.0
        VERSION=$(git describe --tags --abbrev=0 || echo "1.0.0")
        echo "Latest tag: $VERSION"
        
        # Split version into major, minor, patch
        IFS='.' read -r major minor patch <<<"$VERSION"

        # Increment version based on the version type selected
        case ${{ github.event.inputs.version_type }} in
          major)
            major=$((major + 1))
            minor=0
            patch=0
            ;;
          minor)
            minor=$((minor + 1))
            patch=0
            ;;
          patch)
            patch=$((patch + 1))
            ;;
        esac

        # New version after increment
        VERSION="${major}.${minor}.${patch}"
        echo "New version: $VERSION"
        
        # Set the version in the GitHub environment for further steps
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Step to checkout the appropriate branch for INT or PROD
    - name: Checkout the appropriate branch for ${{ github.event.inputs.environment }} environment
      if: github.event_name == 'workflow_dispatch'  # This runs only when the workflow is triggered manually
      run: |
        if [ "${{ github.event.inputs.environment }}" == "INT" ]; then
          git fetch origin int
          git checkout int
        elif [ "${{ github.event.inputs.environment }}" == "PROD" ]; then
          git fetch origin prod
          git checkout prod
        fi
        echo "Checked out the ${GITHUB_REF} branch."

    # Step to build and push the image for INT or PROD environment
    - name: Build and Push image to ECR for INT or PROD environment
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: github-sample
      if: github.event_name == 'workflow_dispatch'  # Runs only when the workflow is triggered manually
      run: |
        IMAGE_TAG="${{ github.event.inputs.environment }}-${{ env.VERSION }}"
        echo "Building and pushing image with tag: $IMAGE_TAG"
        # Build and push the image with the environment and version tag
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "Docker image pushed to ECR with tag: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Output Docker image tag
      run: echo "Docker image pushed with tag:${{ github.event.inputs.environment }}-${{ env.VERSION }}"
