name: Build and Push Docker Image to Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to deploy (DEV, INT, PROD)'
        required: true
        type: choice
        options:
          - DEV
          - INT
          - PROD
      version_type:
        description: 'Choose version type (major, minor, patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch


jobs:
  test-context:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print context variables
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "GitHub Repository: ${{ github.repository }}"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub SHA: ${{ github.sha }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Workflow Name: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "Job Status: ${{ job.status }}"
        echo "Matrix OS: ${{ runner.os }}"
        echo "Matrix Job Name: ${{ job.name }}"
